### ISSUE TITLE
Add support for iter_size - virtual large batch

### ISSUE THREAD

**Issue by okuchaiev** [NVIDIA/OpenSeq2Seq#134]
iter_size should do the following:
1) if iter_size=1 or not set then behave as before
2) if iter_size>1 then we should accumulated gradients on every worker and broadcast/sync every iter_size.

This would effectively mean that "algorithmic batch size" = batch_size_per_gpu*num_gpus*iter_size

**Comment by Kipok** [comment]
Implemented in dev0.4
