### ISSUE TITLE
Suggestions about decoder codes with gnmt attention

### ISSUE THREAD

**Issue by potato1996** [NVIDIA/OpenSeq2Seq#141]
First of all, thanks for your great work!

Here is just a small suggestion about improving the code readability for `RNNDecoderWithAttention` and `BeamSearchDecoderWithAttention` when `gnmt` or `gnmt_v2` attention are enabled, because they confused me when I read them for the first time :)

There's several branches in these two classes when dealing with `gnmt` attentions. I understand branching is necessary for dealing different cases, but some of them are doing quite misleading stuffs, like:
https://github.com/NVIDIA/OpenSeq2Seq/blob/1efa595159426574af4e523a9ee67a3f467b3056/open_seq2seq/decoders/rnn_decoders.py#L384-L390

In the case above this branch force set `residual_connections` and `wrap_to_multi_rnn` to `False`, however it indeed use residual connection below:
https://github.com/NVIDIA/OpenSeq2Seq/blob/1efa595159426574af4e523a9ee67a3f467b3056/open_seq2seq/decoders/rnn_decoders.py#L422-L424

Also, this force overwrites the hparam in configure file, which makes more confusion ( I guess gnmt attention will always the residual connections even if set `False` in configure file?):
https://github.com/NVIDIA/OpenSeq2Seq/blob/1efa595159426574af4e523a9ee67a3f467b3056/example_configs/text2text/en-de-gnmt-like-4GPUs.py#L136

Besides, there are redundant/inconsistent code for creating residual connection: either from `create_rnn_cell`, or by `self._add_residual_wrapper`.

Again thanks for your great work and expecting for new models :)

**Comment by okuchaiev** [comment]
thanks for the feedback @potato1996 ! I agree that this is confusing and param overwrites in the config is some thing we should not do. 
I am going to look into this issue: https://github.com/NVIDIA/OpenSeq2Seq/issues/61 to get rid of `create_rnn_cell` function all together.

**Comment by potato1996** [comment]
> thanks for the feedback @potato1996 ! I agree that this is confusing and param overwrites in the config is some thing we should not do.
> I am going to look into this issue: #61 to get rid of create_rnn_cell function all together.

Thanks!
