### ISSUE TITLE
TensorFlow rnn cells don't have regularizer parameter and thus are difficult to use in MP mode

### ISSUE THREAD

**Issue by Kipok** [NVIDIA/OpenSeq2Seq#153]
The problem is that our MP approach relies on regularization being applied through setting regularizer parameter on a layer or variable level. In case of RNNs it does not seem to be possible because for some reason there is no such parameter and variables are getting created deep inside TF code. The workaround for this would be to write something like this:
```python
for var in rnn_cell.trainable_variables:
  if var.dtype.base_type == tf.float16:
    tf.add_to_collection('REGULARIZATION_FUNCTIONS', (var, self.params["regularizer"]))
```
but seems like a hacky way of fixing this problem and relies on mp_regularizer_wrapper working the way it works now.

**Comment by blisc** [comment]
tf 1.9 has new keras LSTM and CuDNNLSTM layers which accept a regularizer parameter. They seem function as both a rnnCell and rnn layer. I will test and see how well they work.

https://www.tensorflow.org/api_docs/python/tf/keras/layers/CuDNNLSTM

**Comment by devfaizi** [comment]
I would try this too, thanks!
