### ISSUE TITLE
Expose global training step inside hooks.py to model.maybe_print_logs, and finalize_evaluation

### ISSUE THREAD

**Issue by blisc** [NVIDIA/OpenSeq2Seq#154]
For tacotron, I am currently saving images and wav files to disk as opposed to logging them in tensorboard. It would be nice to have access to the current step so I can save the file name for example as eval_sample_step_100.wav.

It would be nice to change inside utils/hooks.py from
dict_to_log = self._model.maybe_print_logs(input_values, output_values)
to
dict_to_log = self._model.maybe_print_logs(input_values, output_values, step)

and from
dict_to_log = self._model.finalize_evaluation(results_per_batch)
to
dict_to_log = self._model.finalize_evaluation(results_per_batch, step)

the downside would be that all models would have to be changed to accept this additional parameter. Alternatively, we could hide it inside input_values or results_per_batch, but this doesn't seem as nice.

**Comment by okuchaiev** [comment]
why can't you use `tf.summary.audio` and `tf.summary.image` summary types to actually store them in Tensorboard?
https://www.tensorflow.org/api_guides/python/summary

**Comment by Kipok** [comment]
Where did you add this to? Can you submit the PR to dev0.4 with that part?

**Comment by Kipok** [comment]
@blisc, can you explain in a bit more details what code and in which place you added to solve the problem?

**Comment by blisc** [comment]
In order to enable tensorboard logging:
  log_summaries_from_dict inside utlis.py has been changed to accept tf.Summary.Value() inside the dict_to_log. dict_to_log can now contain can now contain key, value pairs where the value is a tf.Summary.Value() object. Note in this case, the key is ignored as the Value object already has a tag parameter.

For logging to disk:
  I have a hacky fix where I count the number of times each function is called and just use an internal counter. It probably will not work for continue learning, but this option is more for development.

PS: tensorboard does not play audio on firefox but it works in Chrome.

**Comment by Kipok** [comment]
thanks, @blisc. @okuchaiev, why would not we just pass step into the maybe_print_logs and other functions as was originally proposed? I think there might be other cases why it will be useful information to have and it's not complicated to do it now, while we have just a few modalities.
