### ISSUE TITLE
Overwritting when updating base params with train, eval, and infer params

### ISSUE THREAD

**Issue by blisc** [NVIDIA/OpenSeq2Seq#156]
In the current implementation, scalar parameters are overwritten when the base parms are updated with the train/eval/infer params as intended however it raises an issue for nested parameters in which case the entire dictionary is replaced with what is in the train/eval/infer params . For example:
If my config is
base_params = {
&nbsp;&nbsp;"random_seed":0,
&nbsp;&nbsp;"data_layer_params":{
&nbsp;&nbsp;&nbsp;&nbsp;"num_features":10
&nbsp;&nbsp;}
}
train_params = {
&nbsp;&nbsp;"data_layer_params":{
&nbsp;&nbsp;&nbsp;&nbsp;"dataset":train.csv
&nbsp;&nbsp;}
}

Ideally I would want the train params to be
merged_params = {
&nbsp;&nbsp;"random_seed":0,
&nbsp;&nbsp;"data_layer_params":{
&nbsp;&nbsp;&nbsp;&nbsp;"num_features":10,
&nbsp;&nbsp;&nbsp;&nbsp;"dataset":train.csv
&nbsp;&nbsp;}
}

but currently I get
merged_params = {
&nbsp;&nbsp;"random_seed":0,
&nbsp;&nbsp;"data_layer_params":{
&nbsp;&nbsp;&nbsp;&nbsp;"dataset":train.csv
&nbsp;&nbsp;}
}

It would be helpful for experimentation to leave num_features inside the base params as opposed to adding it to train_params so it can be easily changed via the command line as opposed to creating multiple config files.

**Comment by Kipok** [comment]
Actually, as an afterthought, I think I know how to do what you want. We could use the nested update for the updating base_config with train/eval/infer configs. It's just that current nested_update is a little limited in a sense that it expects the update_dict to have only the elements that are present in the dictionary that is being updated. But that's a few lines of code change. I will try to do it on Monday and see if it works. Or you can try to quickly do that yourself, should be just changing nested_update a bit and changing https://github.com/NVIDIA/OpenSeq2Seq/blob/2f00013c913eccc4353f4132f94a981f7862220f/run.py#L173 and similar lines for eval/infer configs in run.py

**Comment by Kipok** [comment]
Note, that the parameter you want to overwrite will still need to be present in base params, but at least the train_config won't overwrite the whole subdicrionaries only the actual elements that are present in it.
