### ISSUE TITLE
Add batch_size_per_gpu > 1 and num_gpus > 1 inference support for text2text

### ISSUE THREAD

**Issue by Kipok** [NVIDIA/OpenSeq2Seq#172]

**Comment by okuchaiev** [comment]
In general, I am not convinced that inference on more than 1 GPU is necessary. If model really need several GPUs to do inference, then it is probably not a very practical model.
If amount of text to be translated is huge, it can always be split into N chunks and translated in parallel by N processes.

The batch_size > 1 is a valid issue though.

**Comment by chiphuyen** [comment]
Is there any plan to fix the batch_size = 1 issue?
