### ISSUE TITLE
BeamSearchHelperTest.test_shape_list fails with TF 1.9rc2

### ISSUE THREAD

**Issue by nluehr** [NVIDIA/OpenSeq2Seq#176]
TF 1.9 seems to improve static shape inference to pick up constant expressions within the graph. In consequence, all elements returned by `beam_search._shape_list(x)` are now `int` values. This causes the assert on shape[1] in BeamSearchHelperTest.test_shape_list to fail.

**Comment by okuchaiev** [comment]
seems to work with 1.9, closing for now

**Comment by nluehr** [comment]
The change causing this failure does seem to have been reverted between the 1.9 release candidate and the final version. However, it seems to be back in 1.10 final.
