### ISSUE TITLE
Question: Are there any performance numbers available for the models?

### ISSUE THREAD

**Issue by billy19murahmi** [NVIDIA/OpenSeq2Seq#187]
Hi,

The models and recipes page has BLEU score [mentioned.](https://nvidia.github.io/OpenSeq2Seq/html/models-and-recipes.html)

Are there any performance numbers ("no of sentences per second" or "Seconds per step") for those configuration?

Thanks,
Srini

**Comment by okuchaiev** [comment]
No. Perf numbers depend heavily on hardware used and exact software setup, so consistently measuring them isn't a trivial effort.
