### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by syed-ahmed** [NVIDIA/OpenSeq2Seq#2]
Can we get a pretrained model? :)

**Comment by okuchaiev** [comment]
We do have a reference config, so that you can reproduce in 1 GPU-day. 

The trouble of actually releasing a pre-trained model is that these models are quite big. 
Leaving this open for now because I don't have a good way of releasing huge files.

**Comment by okuchaiev** [comment]
added a link to pre-trained model
