### ISSUE TITLE
No dataset augmentation in Wave2Letter+ models

### ISSUE THREAD

**Issue by jakepoz** [NVIDIA/OpenSeq2Seq#229]
The DeepSpeech 2 model includes dataset augmentation of time stretch and some Gaussian noise. 
[Link](https://nvidia.github.io/OpenSeq2Seq/html/speech-recognition/deepspeech2.html)

Why does the Wave2Letter model not do the same thing?

**Comment by borisgin** [comment]
Yes, you can add the data augmentation to Wave2Letter. I would recommend to try Wave2LetterPlus instead (it gives  better WER).
