### ISSUE TITLE
ValueError: Internal error occurred mkl_fft

### ISSUE THREAD

**Issue by RaymondNie** [NVIDIA/OpenSeq2Seq#235]
After following the installation instructions for OpenSeq2Seq and running the first test:
```
python run.py --config_file=example_configs/speech2text/ds2_toy_config.py --mode=train_eval
```
I received a ValueError: Internal error occurred related to mkl_fft causing the test to fail.

As a temporary fix found from https://github.com/IntelPython/mkl_fft/issues/11, the test ran properly after adding the following line at the top of the file  OpenSeq2Seq/open_seq2seq/data/speech2text.py to disable mkl optimization.

```
np.fft.restore_all()
```

Additional Details:
- Tensorflow version 1.10.0
- CUDA 9.2
- cuDNN 7.3
- Python 3.6

**Comment by okuchaiev** [comment]
@RaymondNie is this still a problem on 18.11-dev?

**Comment by RaymondNie** [comment]
No longer had this issue when setting up OpenSeq2Seq.
