### ISSUE TITLE
race condition with logdir while launching distributed training job with horovod

### ISSUE THREAD

**Issue by vsuthichai** [NVIDIA/OpenSeq2Seq#236]
There may be a race condition when launching a distributed training job with --enable_logs turned on.  On the master node with 8 gpus, I'm noticing that I'll seem to randomly get this error `"Log directory is not empty. If you want to continue learning, you should provide "--continue_learning" flag"` accompanied by 1 or more GPUs not being acquired.  I believe it has to do with the the rank 0 process creating the logdir and other ranks checking for its existence and a checkpoint within.  The logging directory is created first and other ranks will try to find a checkpoint afterward.  They'll fail and an IOError will be raised and caught.  The `checkpoint` variable is never set when being returned from `check_logdir` and finally the process seems to just hang never acquiring its GPU.  Horovod shuts down moments later with an error.

https://github.com/NVIDIA/OpenSeq2Seq/blob/296bad175c171feb994285edd94d89c5f08e8b38/run.py#L36

https://github.com/NVIDIA/OpenSeq2Seq/blob/296bad175c171feb994285edd94d89c5f08e8b38/open_seq2seq/utils/utils.py#L578

Adding one line of code here fixes the problem for me.  Happy to submit a PR.
```python3
  # Check logdir and create it if necessary
  if hvd is None or hvd.rank() == 0:
    checkpoint = check_logdir(args, base_config, restore_best_checkpoint)
```

**Comment by okuchaiev** [comment]
Hi @vsuthichai . Yes, please submit PRs based on 18.11-dev. Thanks!

**Comment by blisc** [comment]
If we want to be sure, why don't we add a blocking call right after Horovod init?
`
  # Initilize Horovod
  if base_config['use_horovod']:
    import horovod.tensorflow as hvd
    hvd.init()
    if hvd.rank() == 0:
      deco_print("Using horovod")
    from mpi4py import MPI
MPI.COMM_WORLD.Barrier()
`

I'm assuming that MPI.COMM_WORLD.Barrier() implements such a call

**Comment by vsuthichai** [comment]
@blisc That sounds like a better fix

**Comment by okuchaiev** [comment]
@blisc PR?
