### ISSUE TITLE
iter_size set to 1 with transformer distributed training for horovod

### ISSUE THREAD

**Issue by vsuthichai** [NVIDIA/OpenSeq2Seq#244]
When training a transformer model, doing a horovod `allreduce` with `iter_size` set to 1 and `hvd.size() > 1` results in going down a very inefficient Horovod `allgather` path for the embedding matrix.  Essentially, Tensorflow tries to do a sparse and dense gradient update for the embedding matrix and uses an `IndexedSlices` object for the gradient representation.  When `iter_size` is greater than 1, `tf.scatter_nd_add` takes care of summing the values for duplicate indices.  This logic does not get executed when `iter_size` is set to 1.  I've tried a few workaround for this.  I've deduped the indices manually and summed the values, resulting in a dense tensor which circumvents `allgather` and forces `allreduce`.  I've also forced the existing codepath to go down the `tf.scatter_nd_add` route by changing the logic such that `iter_size >= 1` which also results in a dense tensor to avoid `allgather`.

https://github.com/NVIDIA/OpenSeq2Seq/blob/87e9625af99b799808d5d9af8147f8ee4a2c5dbe/open_seq2seq/optimizers/optimizers.py#L80-L89

https://github.com/NVIDIA/OpenSeq2Seq/blob/87e9625af99b799808d5d9af8147f8ee4a2c5dbe/open_seq2seq/optimizers/optimizers.py#L207-L209

https://github.com/uber/horovod/blob/8d72d66738037acad8517da95d5d76e773e7117a/horovod/tensorflow/__init__.py#L67-L78

#204

**Comment by okuchaiev** [comment]
Could you please send a PR? just setting iter_size >=1 gives me an error... Interestingly if I set iter_size=2 in config it works.

**Comment by vsuthichai** [comment]
@okuchaiev  So, these are workarounds I've tried:

Workaround 1. This is currently my `reduce_gradients` function.  I'm handling the `IndexedSlices` object here so that it avoid Horvod's allgather.  It really only comes into play when iter_size is 1.  When it is greater than 1, it follows the `tf.scatter_nd_add` code path.

```python
def reduce_gradients(grads_and_vars, on_horovod):
  if on_horovod:
    from horovod.tensorflow import size
    from horovod.tensorflow import allreduce
    from tensorflow.python.training.optimizer import _deduplicate_indexed_slices

    if size() > 1:
      averaged_grads_and_vars = []
      with tf.name_scope("all_reduce"):
        for grad, var in grads_and_vars:
          """
          if grad is not None:
            avg_grad = allreduce(grad)
            averaged_grads_and_vars.append((avg_grad, var))
          else:
            averaged_grads_and_vars.append((None, var))
          """

          if grad is not None:
            _grad = grad
            if isinstance(grad, tf.IndexedSlices):
              summed_values, unique_indices = _deduplicate_indexed_slices(
                values=grad.values, indices=grad.indices)
              gradient_no_duplicate_indices = tf.IndexedSlices(
                indices=unique_indices,
                values=summed_values,
                dense_shape=grad.dense_shape)
              _grad = tf.convert_to_tensor(gradient_no_duplicate_indices)
            avg_grad = allreduce(_grad)
            averaged_grads_and_vars.append((avg_grad, var))
          else:
            averaged_grads_and_vars.append((None, var))
      return averaged_grads_and_vars
    else:
      return grads_and_vars
  else:
    raise NotImplementedError("Reduce in tower-mode is not implemented.")
```

Workaround 2.   I made a few changes throughout the codebase to handle `iter_size` appropriately such that it always follows the `tf.scatter_nd_add` code path even when I configure `iter_size` to be 1.  This effectively does the same thing as workaround 1 but is really intended to store accumulated gradients.  It feels wasteful though because extra vars are still created even though `iter_size` is 1.

Any thoughts on this?

**Comment by okuchaiev** [comment]
my worry is this line: _grad = tf.convert_to_tensor(gradient_no_duplicate_indices)  - effectively it converts sparse tensor into dense which can waste memory. Not sure how to workaround this and I think we could be doing it for iter_size>=2 anyway

**Comment by vsuthichai** [comment]
For the transformer model, the embedding matrix gradients are represented as IndexedSlices even though it is really a dense _and_ sparse update.  This is because it's used as the projection matrix just before the softmax and as the embeddings that are fed in at the input layer.  Even though a sparse tensor representation is being used, it really should be dense.  Checking the size of the resulting `allgather`, it can be verified that the size of the IndexedSlices is at least the size of the vocabulary, so it really shouldn't be represented sparsely, but somehow Tensorflow treats it as such.

**Comment by okuchaiev** [comment]
somehow I still get 
**
File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/optimizers/optimizers.py", line 257, in optimize_loss
    false_fn=update_and_clear_op,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2037, in cond
    p_2, p_1 = switch(pred, pred)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 348, in switch
    data, dtype=dtype, name="data", as_ref=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1255, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 424, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

**

TMP branch using your reduce_gradients function
https://github.com/NVIDIA/OpenSeq2Seq/blob/18.11-tmp/open_seq2seq/optimizers/optimizers.py

**Comment by vsuthichai** [comment]
set this line
https://github.com/NVIDIA/OpenSeq2Seq/blob/aa7ea9b898756f182453cf83eaadca4e7041375e/open_seq2seq/optimizers/optimizers.py#L212

back to

```python
 if iter_size == 1: 
```

**Comment by vsuthichai** [comment]
I can submit a PR :)

**Comment by vsuthichai** [comment]
Going 4+ nodes (32 gpus), you should see a difference.   It should not crash due to OOM.

**Comment by vsuthichai** [comment]
@okuchaiev I've been thinking about what you mentioned earlier, and I agree that converting sparse to dense can be memory intensive for other models that are not the transformer.  The workaround I had in place with reduce_gradients seems like it should only be executed if we know the model is a transformer model.  So I'm trying to add checks within `reduce_gradients` or `optimize_loss` to see if the model is a transformer model, but there doesn't seem to be an easy way to look for this information without changing function signatures of `optimize_loss`.

**Comment by okuchaiev** [comment]
I think we can close this for now. Thanks!
