### ISSUE TITLE
Unable to use the docker image

### ISSUE THREAD

**Issue by rahul003** [NVIDIA/OpenSeq2Seq#272]
Running into this error when I do `cd OpenSeq2Seq; sudo docker build -t openseq2seq .`

```
Sending build context to Docker daemon  83.85MB
Step 1/40 : FROM gitlab-dl.nvidia.com:5005/dgx/tensorflow:18.04-py2-devel
Get https://gitlab-dl.nvidia.com:5005/v2/: dial tcp: lookup gitlab-dl.nvidia.com on 127.0.0.53:53: no such host
```

**Comment by vsl9** [comment]
Please try official NVIDIA TensorFlow Docker container: https://www.nvidia.com/en-us/gpu-cloud/deep-learning-containers/
It contains OpenSeq2Seq in `/workspace/nvidia-examples/OpenSeq2Seq` directory.
