### ISSUE TITLE
Import Speech2TextDataLayer fails

### ISSUE THREAD

**Issue by lukeinator42** [NVIDIA/OpenSeq2Seq#278]
Hi,

I tried running the interactive infer example in the jupyter notebook, but I'm getting the error ValueError: data_layer parameter has to be specified. Is this something I have to set in the config?

Also, when I try importing the layer by running:
`from open_seq2seq.data import Speech2TextDataLayer`

I get the error
ImportError: cannot import name 'WKTDataLayer'

Any help would be greatly appreciated!

**Comment by blisc** [comment]
Your config file is most likely missing the interactive_infer_params dictionary.
For example w2lplus_large_8gpus_mp.py has this at the end of the config file

`infer_params = {
    "data_layer": Speech2TextDataLayer,
    "data_layer_params": {
        "num_audio_features": 64,
        "input_type": "logfbank",
        "vocab_file": "open_seq2seq/test_utils/toy_speech_data/vocab.txt",
        "dataset_files": [
            "data/librispeech/librivox-test-clean.csv",
        ],
        "shuffle": False,
    },
}`

It would suffice to add the following to the config file:

`infer_params = {
    "data_layer": Speech2TextDataLayer,
    "data_layer_params": {
        "num_audio_features": 64,
        "input_type": "logfbank",
        "vocab_file": "open_seq2seq/test_utils/toy_speech_data/vocab.txt",
        "dataset_files": [
            "data/librispeech/librivox-test-clean.csv",
        ],
        "shuffle": False,
    },
}

interactive_infer_params = {
    "data_layer": Speech2TextDataLayer,
    "data_layer_params": {
        "num_audio_features": 64,
        "input_type": "logfbank",
        "vocab_file": "open_seq2seq/test_utils/toy_speech_data/vocab.txt",
        "dataset_files": [],
        "shuffle": False,
    },
}`

**Comment by lukeinator42** [comment]
ah yup, I was missing that. Thanks!
