### ISSUE TITLE
LARC eta, lr, and multi-node training

### ISSUE THREAD

**Issue by bmwshop** [NVIDIA/OpenSeq2Seq#284]
Any guidelines on multi-node training of speech2text  and text2text models as we go beyond 8 GPUs ? Should we try to proportionally increase the larc eta, for instance?

**Comment by borisgin** [comment]
I did not train speech on multi-nodes. For ResNet-like nets, we usually increase both LARC eta and  LR as ~k* sqrt(B) . Also when we double batch we increase number of epochs by ~ 20% , so effectively the number of iterations  is x 0.6.
