### ISSUE TITLE
Does Inference work on CPU alone?

### ISSUE THREAD

**Issue by sruteesh-pivot** [NVIDIA/OpenSeq2Seq#289]
Hello ,
I tried running the inference using a CPU machine. But I keep getting this error
```
NameError: name 'build_forward_pass_graph_fn' is not defined
```

Does the script not support inference/training on CPU.

Thanks.

**Comment by vsl9** [comment]
Which version / branch do you use? Can you please try the latest master branch? It doesn't have any ```build_forward_pass_graph_fn``` in the code.

**Comment by sruteesh-pivot** [comment]
Hi,
I tried with `use_horovod` =False and I was getting shape mismatch error.
I guess I was trying to use the mixed precision model on my CPU and hence the errors.

I was able to sucessfully infer using the wiki2-fp32 model.

Thanks.

**Comment by ffxz** [comment]
how do you use cpu to infer

**Comment by ffxz** [comment]
how do you use cpu to infer? @sruteesh-pivot
