### ISSUE TITLE
Question: Ho to feed Style Token to Tacotron in inference?

### ISSUE THREAD

**Issue by ErnstTmp** [NVIDIA/OpenSeq2Seq#296]
Hello,
thanks for creating and open sourcing OpenSeq2Seq!!!

I am training Tacotron GST, and I would like to provide different Global Style Tokens (GST) as mentioned in the paper to the Tacotron during inference. How can I do that? How can I construct the tokens?

Thank you very much and kind regards
Ernst

**Comment by blisc** [comment]
This is not currently supported. If you wanted to try, I would suggest to run in interactive infer and create a placeholder for the tokens inside the data layer.

**Comment by mrgloom** [comment]
@blisc 

Looking at 
https://github.com/NVIDIA/OpenSeq2Seq/blob/master/Interactive_Infer_example.ipynb
https://nvidia.github.io/OpenSeq2Seq/html/interactive-infer-demos.html
it's not clear how to add this functionality.

As I understand style token should be added as new input:
https://github.com/NVIDIA/OpenSeq2Seq/blob/master/open_seq2seq/data/text2speech/text2speech.py#L603
https://github.com/NVIDIA/OpenSeq2Seq/blob/master/open_seq2seq/data/text2speech/text2speech.py#L634
https://github.com/NVIDIA/OpenSeq2Seq/blob/master/open_seq2seq/data/text2speech/text2speech.py#L590

But should we retrain model or modify existing graph somehow to make it possible?

**Comment by blisc** [comment]
You would have to create a new placeholder in create_interactive_placeholders() and modify tacotron 2 encoder such that `style_embedding = self._embed_style(style_spec, style_len)` becomes `style_embedding = input_dict['source_tensors'][X]`
