### ISSUE TITLE
Jasper models

### ISSUE THREAD

**Issue by bmwshop** [NVIDIA/OpenSeq2Seq#305]
We are seeing really interestng results with Jasper models on noisy data.  Could you possibly comment on the impact of dataset  augmentation with generated speech and also on the increasing of the depth of the model? e.g. if we double the data set, does it improve WER for the same model or does it allow us to train a deeper model without an overfit?

**Comment by borisgin** [comment]
Do you mean if we add 2x of syntetic data to natural data set? This can hurt your testing Wer , eg when syntetic set is generated with only one voice, so model
Will overfit this speaker

**Comment by bmwshop** [comment]
I meant just one generated voice, so (original dataset + generated) == 2 * size of original.
We are training the largest Jasper model on a combination of Fisher (2,000 hours ) + libri (1,000 hours) == 3,000 hours. So the question is [a] should we augment - effectively double the size of the data set to 6,000 hours and if so, [b] should we make the Jasper model deeper?

**Comment by GabrielLin** [comment]
Hi @bmwshop , could you please share your training time and what GPU you used for training jasper. It costs me about 8 days for training w2l_large_8gpus_mp on 8x 1080TI. So long!

**Comment by okuchaiev** [comment]
@GabrielLin , w2l_large_8gpus_mp is *mixed precision* config. It should not work on 1080Ti, unless you change dtype to float32.   Is this what you did?

**Comment by GabrielLin** [comment]
@okuchaiev . Really really thanks. You gave me a great reminder. I have not got this detail before. I will retrain my model. 

By the way, if I use pre-train mixed models for inference on 1080TI, is it OK?

**Comment by Shujian2015** [comment]
Hi @bmwshop, do you mind sharing the training time of Jasper 10*5 on Fisher+swbd?
