### ISSUE TITLE
Progressbar issues with import_librivox.py

### ISSUE THREAD

**Issue by David-Levinthal** [NVIDIA/OpenSeq2Seq#308]
I ran into a sequence of issues using import_librivox.py
1) progressbar uses maxval not maxvalue
2)progressbar uses widgets not widget
C:\Users\dlevinth\machine_learning\deepspeech2>diff import_librivox.py import_librivox_orig.py
33,34c33
<   #with progressbar.ProgressBar(max_value=7, widget=progressbar.AdaptiveETA) as bar:
<   with progressbar.ProgressBar(maxval=7, widgets=progressbar.AdaptiveETA) as bar:
but then I ran into the following which I am unclear on how to resolve
levinth@moxli001:~/OpenSeq2Seq$ python3.6 scripts/import_librivox.py data/librispeech
Downloading Librivox data set (55GB) into data/librispeech if not already present...
Traceback (most recent call last):
  File "scripts/import_librivox.py", line 190, in <module>
    _download_and_preprocess_data(sys.argv[1])
  File "scripts/import_librivox.py", line 34, in _download_and_preprocess_data
    with progressbar.ProgressBar(maxval=7, widgets=progressbar.AdaptiveETA) as bar:
  File "/usr/local/lib/python3.6/site-packages/progressbar/progressbar.py", line 120, in __init__
    self._update_widgets()
  File "/usr/local/lib/python3.6/site-packages/progressbar/progressbar.py", line 240, in _update_widgets
    for w in self.widgets)
TypeError: 'ABCMeta' object is not iterable

this is on ubuntu16.04.5 with python3.6 built from source in /usr/src with sudo

**Comment by David-Levinthal** [comment]
I followed the installation instructions
and installed the following missing packages
sudo pip3.6 install progressbar
sudo apt-get install sox libsox-dev libsox-fmt-all
sudo pip3.6 install sox

should I remove progressbar and install tqdm instead?

**Comment by vsl9** [comment]
Sure. We don't use `progressbar` now. All required Python packages should be in `requirements.txt`.

**Comment by David-Levinthal** [comment]
thanks for replacing progressbar with tqdm
did the trick..
