### ISSUE TITLE
generate_trie eat whole system memory!

### ISSUE THREAD

**Issue by dingguijin** [NVIDIA/OpenSeq2Seq#326]
ctc_decoder_with_lm/generate_trie eat all memory of system (32G) and killed by system.

Since my 4-gram binary file is  almost 8G. Suggest read a block and write back to file not read everything into memory.

**Comment by borisgin** [comment]
Can you check, please, what happens if you change POPULATE_OR_READ to LAZY or to POPULATE_OR_LAZY in generate_trie.cpp
  config.load_method = util::LAZY;
