### ISSUE TITLE
having trouble reproducing DS2 result

### ISSUE THREAD

**Issue by byan23** [NVIDIA/OpenSeq2Seq#327]
I was trying to reproduce the claimed result for DS2 but failed... I was able to get to 9.0 (WER) with 8 gpus after 50 epochs (108k iters)
env detail:
8 * 1080 Ti gpus. 
I used the original config file ds2_large_8gpus_mp.py.

I noticed that https://nvidia.github.io/OpenSeq2Seq/html/speech-recognition/deepspeech2.html mentioned that I need to train for 200 epochs which conflicts with the config file.
Can I get a 6.71 WER with --num_epochs=200 using ds2_large_8gpus_mp.py?

I've also noticed that the checkpoint provided in the above link is a result after only 54k iters. Assuming running on a single node with 8 gpus, batch_size_per_gpu=16 (based on ds2_large_8gpus_mp.py). I did some quick math here: 54k * 8 * 16 / 280k utterances = 24 epochs.
To match the claimed 200 epochs, sounds like the checkpoint is actually a result of 8 node (200 / 24) ..?

These don't sound right to me. Could any of you help out on this? Thanks.

**Comment by borisgin** [comment]
DS2 was trained on 1 node with 8 GPU (V100x16GB). It took 200 epochs (you can change it in config file or overwrite from command line).
Please note that 1080 Ti don’t support mixed precision in full, so I would suggest to use float32 precision on these cards

**Comment by borisgin** [comment]
Yes, WER should be the same

**Comment by byan23** [comment]
I am able to reproduce the result. Thanks for the help!
