### ISSUE TITLE
Error during bazel build

### ISSUE THREAD

**Issue by Bancherd-DeLong** [NVIDIA/OpenSeq2Seq#328]
System: ubuntu 16.04, RAM 32GBytes, single GPU=gtx1080. Using "Anaconda3-5.0.1"  I modified _**generate_trie.cpp**_ to "config.load_method = util::LAZY;"   I was following instructions from "https://nvidia.github.io/OpenSeq2Seq/html/installation.html#installation-speech":

`INFO: From Executing genrule //tensorflow/contrib/ignite:gen_igfs_ops_pygenrule:
2019-01-06 06:01:13.025577: I tensorflow/contrib/ignite/kernels/igfs/igfs.cc:68] IGFS created [host=localhost, port=10500, fs_name=default_fs]
INFO: From Compiling tensorflow/contrib/factorization/kernels/wals_solver_ops.cc:
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/core/lib/core/status.h:25,
                 from ./tensorflow/core/framework/op_def_builder.h:25,
                 from ./tensorflow/core/framework/op.h:23,
                 from tensorflow/contrib/factorization/kernels/wals_solver_ops.cc:26:
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::__cxx11::string* tensorflow::internal::Check_LEImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = long long int; std::__cxx11::string = std::__cxx11::basic_string<char>]':
tensorflow/contrib/factorization/kernels/wals_solver_ops.cc:195:5:   required from here
./tensorflow/core/platform/default/logging.h:261:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
                                   ^
./tensorflow/core/platform/macros.h:88:49: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                 ^
./tensorflow/core/platform/default/logging.h:261:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
 ^
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::__cxx11::string* tensorflow::internal::Check_LEImpl(const T1&, const T2&, const char*) [with T1 = long long int; T2 = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]':
tensorflow/contrib/factorization/kernels/wals_solver_ops.cc:240:7:   required from here
./tensorflow/core/platform/default/logging.h:261:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
                                   ^
./tensorflow/core/platform/macros.h:88:49: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                 ^
./tensorflow/core/platform/default/logging.h:261:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
 ^
ERROR: missing input file '@pasta//:LICENSE'
ERROR: /home/bancherd2/tensorflow/tensorflow/tools/pip_package/BUILD:235:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@pasta//:LICENSE'
ERROR: /home/bancherd2/tensorflow/tensorflow/tools/pip_package/BUILD:235:1 1 input file(s) do not exist
INFO: Elapsed time: 367.486s, Critical Path: 73.60s
INFO: 314 processes: 314 local.
FAILED: Build did NOT complete successfully
.....................................................................................

Any suggestions?  Thank you.`

**Comment by borisgin** [comment]
Can you clean hazel cache and retry please?
bazel clean --expunge

**Comment by Bancherd-DeLong** [comment]
Sorry, it is still there, at different location:

`                            ^
INFO: From Compiling tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc:
tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc: In member function 'tensorflow::Status tensorflow::data::{anonymous}::SequenceFileReader::ReadHeader()':
tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc:76:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < num_metadata_pairs; i++) {
                       ^
tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc: In member function 'tensorflow::Status tensorflow::data::{anonymous}::SequenceFileReader::ReadVInt(tensorflow::int64*)':
tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc:156:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < buffer.size(); i++) {
                       ^
In file included from tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc:16:0:
./tensorflow/core/framework/dataset.h: In instantiation of 'tensorflow::Status tensorflow::data::GraphDefBuilderWrapper::AddVector(const std::vector<_RealType>&, tensorflow::Node**) [with T = std::__cxx11::basic_string<char>]':
tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc:241:7:   required from here
./tensorflow/core/framework/dataset.h:112:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < val.size(); i++) {
                       ^
INFO: From Compiling tensorflow/contrib/tensor_forest/kernels/model_ops.cc:
In file included from ./tensorflow/contrib/tensor_forest/kernels/v4/leaf_model_operators.h:19:0,
                 from ./tensorflow/contrib/tensor_forest/kernels/v4/decision-tree-resource.h:21,
                 from tensorflow/contrib/tensor_forest/kernels/model_ops.cc:19:
./tensorflow/contrib/tensor_forest/kernels/v4/input_target.h: In member function 'virtual float tensorflow::tensorforest::TensorInputTarget::GetTargetWeight(int) const':
./tensorflow/contrib/tensor_forest/kernels/v4/input_target.h:71:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     return num_weights > 0 && example_index < num_weights
                                             ^
tensorflow/contrib/tensor_forest/kernels/model_ops.cc: In member function 'virtual void tensorflow::tensorforest::TreePredictionsV4Op::Compute(tensorflow::OpKernelContext*)':
tensorflow/contrib/tensor_forest/kernels/model_ops.cc:233:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < tree_paths.size(); ++i) {
                       ^
In file included from ./tensorflow/core/lib/strings/strcat.h:27:0,
                 from ./tensorflow/core/lib/strings/str_util.h:23,
                 from ./tensorflow/contrib/tensor_forest/kernels/data_spec.h:23,
                 from tensorflow/contrib/tensor_forest/kernels/model_ops.cc:18:
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetTensorDim(tensorflow::gtl::ArraySlice<T>, tensorflow::TensorFormat, char) [with T = long long int; tensorflow::gtl::ArraySlice<T> = absl::Span<const long long int>]':
./tensorflow/core/util/tensor_format.h:452:47:   required from here
./tensorflow/core/util/tensor_format.h:420:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attributes.size())
                             ^
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:420:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attributes.size())
   ^
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetFilterDim(tensorflow::gtl::ArraySlice<T>, tensorflow::FilterTensorFormat, char) [with T = long long int; tensorflow::gtl::ArraySlice<T> = absl::Span<const long long int>]':
./tensorflow/core/util/tensor_format.h:461:54:   required from here
./tensorflow/core/util/tensor_format.h:435:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attribute.size())
                             ^
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:435:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attribute.size())
   ^
INFO: From Compiling tensorflow/contrib/framework/kernels/zero_initializer_op_gpu.cu.cc:
external/com_google_absl/absl/strings/string_view.h(496): warning: expression has no effect

external/com_google_absl/absl/strings/string_view.h(496): warning: expression has no effect

INFO: From ProtoCompile tensorflow/contrib/rpc/python/kernel_tests/test_example.pb.cc:
bazel-out/k8-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
ERROR: missing input file '@pasta//:LICENSE'
ERROR: /home/bancherd2/tensorflow/tensorflow/tools/pip_package/BUILD:235:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@pasta//:LICENSE'
ERROR: /home/bancherd2/tensorflow/tensorflow/tools/pip_package/BUILD:235:1 1 input file(s) do not exist
INFO: Elapsed time: 6785.228s, Critical Path: 284.49s
INFO: 15309 processes: 15309 local.
FAILED: Build did NOT complete successfully

-----------------------------------------------------
Thank you for looking into this.`

**Comment by Bancherd-DeLong** [comment]
I will remove "@pasta//:LICENSE", and try again tomorrow.  Thanks.
