### ISSUE TITLE
Pre-trained transformer models

### ISSUE THREAD

**Issue by sundeepteki** [NVIDIA/OpenSeq2Seq#331]
Hi,

Do you've an ETA for releasing Transformer pre-trained models for the following models - 

"It is very good for neural machine translation tasks and base configuration achieves SacreBLEU of 26.4 on WMT 2014 English-to-German translation task ( checkpoint TBD ) while big model gets around 27.5."

**Comment by vsl9** [comment]
Hi,

Thank you for catching this TBD in the documentation! You can find the checkpoints on the main machine translation page: https://nvidia.github.io/OpenSeq2Seq/html/machine-translation.html

**Comment by sundeepteki** [comment]
Thanks for sharing!
