### ISSUE TITLE
stt model training question

### ISSUE THREAD

**Issue by wujsy** [NVIDIA/OpenSeq2Seq#334]
Hi, for speech to text in chinese ,what are the differences between alphabet.txt and vocabulary.txt? Are they both necessary?

**Comment by wujsy** [comment]
How to generate the trie file for chinese ?

**Comment by borisgin** [comment]
We did not train ASR for Chinese

**Comment by mcggood** [comment]
> See for example [https://blog.yuwu.me/?p=3989](url) , starting from 11.

the link can't be reached. Would you share again?
