### ISSUE TITLE
Tacotron GST cuDNN launch failure

### ISSUE THREAD

**Issue by stefbraun** [NVIDIA/OpenSeq2Seq#337]
Hi, I am trying to train tacotron-gst on a single GPU (11GB 2080 Ti). However, I get a CUDNN launch failure (see below). Can anyone help with this? Thanks

Versions:
Ubuntu 16.04
Tensorflow 1.10
CUDA 9.0.176
CUDNN 7.0.5

Train-options:
num_gpu=1
batch-size: 16

*** Epoch 0, global step 0: ***     Train loss: 24.9268 
time per step = 0:00:0.420
WARNING: Train_mag audio was clipped at step 0
WARNING: Train audio was clipped at step 0
2019-01-14 13:39:53.899786: E tensorflow/stream_executor/cuda/cuda_dnn.cc:81] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(2454): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd.handle(), input_data.opaque(), filter.handle(), filter_data.opaque(), conv.handle(), ToConvForwardAlgo(algo_desc), scratch.opaque(), scratch.size(), beta, output_nd.handle(), output_data->opaque())'
Traceback (most recent call last):
  File "/home/brauns/anaconda3/envs/oseq/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/brauns/anaconda3/envs/oseq/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/brauns/anaconda3/envs/oseq/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
**tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape([16,1,1,169]) filter shape([1,32,1,32])**
	 [[Node: ForwardPass/tacotron_2_decoder/decoder/while/BasicDecoderStep/decoder/attention_wrapper/location_attention/location_conv/conv1d/Conv2D = Conv2D[T=DT_FLOAT, _class=["loc:@Loss_...ad/Reshape"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ForwardPass/tacotron_2_decoder/decoder/while/BasicDecoderStep/decoder/attention_wrapper/location_attention/location_conv/conv1d/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, ForwardPass/tacotron_2_decoder/decoder/while/BasicDecoderStep/decoder/attention_wrapper/location_attention/location_conv/conv1d/ExpandDims_1)]]
	 [[Node: ForwardPass/Loss/tacotron_loss/mean_squared_error/num_present/broadcast_weights/assert_broadcastable/AssertGuard/Assert/Switch_1/_2881 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2840_...t/Switch_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by blisc** [comment]
Please update cuda to 10.0 and cudnn to 7.4 as support for Turing cards was added recently.

Afterwards, can you try running it inside our docker container? So that we can eliminate issues between tensorflow and other library versions.
[See here for instructions on using the docker.](https://github.com/NVIDIA/OpenSeq2Seq/issues/329#issuecomment-453193910)

Let us know if the issue persists

**Comment by trevor-m** [comment]
@blisc 
I am encountering the same segfault issue. I am using the `gitlab-master.nvidia.com:5005/dl/dgx/tensorflow:master-py3-devel` container but I have compiled tensorflow from the upstream master branch. I have CUDA 10.0.130 and cudnn 7.4 patch 2.

**Comment by borisgin** [comment]
yes, we see this issue only with latest TF maser. Nvidia container "1.12" should be ok.

**Comment by borisgin** [comment]
What is the location of the downloadef dataset? Is it under root /dataset:...?

**Comment by blisc** [comment]
The MAILABS dataset is not well organized. There exists files inside the csv that does not have audio clips. You will have to manually remove these from the csv.

I’ll add a note to the docs

**Comment by zhengwy888** [comment]
add this one line would filter non-existing file out.

```python
    cleaned = files[files.apply(lambda x: os.path.exists(os.path.join(data_root, x['1'] + '.wav')), axis=1)]
```
