### ISSUE TITLE
CUDNN optimal algorithm search

### ISSUE THREAD

**Issue by fminkin** [NVIDIA/OpenSeq2Seq#344]
Hello, I noticed that speech to text models (I tried out jasper) have very long "preheating stage".

E.G. first several thousands batches is really slow, and then the network fixes the algorithm and becomes steadily fast. 

enviromental variable TF_CUDNN_USE_AUTOTUNE=0 fixes the problem, but TF_CUDNN_USE_AUTOTUNE=1 network after several hours of preheating overtakes network with autotune and becomes faster.

Do you have some insight on how to fix that behaviour or how to appropriately preheat the model?

**Comment by borisgin** [comment]
Do you see this behavior on local machine, or this is on cluster?
Btw, currently there is no way to set cudnn_algorithm in TF manually.

**Comment by fminkin** [comment]
I'm using cluster with 8 v100.

**Comment by fminkin** [comment]
Dataset is stored locally, and I'm also reading features instead of wav files. You can try it out by freezing one of your models and get timings for 1000 batches.
