### ISSUE TITLE
TypeError: failed to train tacotron model for chinese dataset

### ISSUE THREAD

**Issue by wujsy** [NVIDIA/OpenSeq2Seq#346]
Hi, I used tacotron model to train chinese dataset, but type errors happened:
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: magphase() got an unexpected keyword argument 'power'
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/data/workspace/OpenSeq2Seq/open_seq2seq/data/text2speech/text2speech.py", line 442, in _parse_audio_transcript_element
    mel_basis=self._mel_basis

  File "/data/workspace/OpenSeq2Seq/open_seq2seq/data/text2speech/speech_utils.py", line 87, in get_speech_features_from_file
    hop_length, mag_power, feature_normalize, mean, std, data_min, mel_basis

  File "/data/workspace/OpenSeq2Seq/open_seq2seq/data/text2speech/speech_utils.py", line 147, in get_speech_features
    mag, _ = librosa.magphase(complex_spec, power=mag_power)

TypeError: magphase() got an unexpected keyword argument 'power'

	 [[{{node PyFuncStateless}} = PyFuncStateless[Tin=[DT_STRING], Tout=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_INT32], token="pyfunc_0", _device="/device:GPU:0"](arg0)]]
	 [[node IteratorGetNext (defined at /data/wujiaxing/workspace/OpenSeq2Seq/open_seq2seq/data/text2speech/text2speech.py:338)  = IteratorGetNext[output_shapes=[[?,?], [?,1], [?,?,593], [?,?], [?,1]], output_types=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
	 [[{{node ForwardPass/tacotron_2_decoder/decoder_1/stop_token_proj/Tensordot/GatherV2/_1805}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1888_...t/GatherV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

what's the problem?

**Comment by borisgin** [comment]
Which librosa version do you have?

**Comment by borisgin** [comment]
Did you try to reduce the number of features in the spectrogram?

**Comment by wujsy** [comment]
yes, the problem was solved by reducing the number of features, thanks @ borisgin
