### ISSUE TITLE
How to add domain specific keyword 

### ISSUE THREAD

**Issue by AIGyan** [NVIDIA/OpenSeq2Seq#367]
Hello NVIDIA team,
Thank you for the fantastic work. 
I used the model and found the model lags in transcription of the domain specific key word and local slang.
Can you please provide me some guidance to improve the transcription accuracy.

Thanks once again for the help.

**Comment by borisgin** [comment]
You need to retune the model if the domain is different from the used dataset

**Comment by AIGyan** [comment]
Thanks. Is the training need audio + Transcript ? or Only Audio ?

**Comment by borisgin** [comment]
For training you need both audio and transcript. If the target dictionary is small, please check the models in "Speech commands" section
