### ISSUE TITLE
Tacotron : inference producing bad results after training

### ISSUE THREAD

**Issue by mehulsuresh** [NVIDIA/OpenSeq2Seq#369]
Tried to follow instructions to train tacotron on LJ speech dataset. The model converges but I am not able to produce good results in inference for example : https://drive.google.com/open?id=1Gozn18jlzgu0_yja8z9_hJraRlBsnbSa Which is completely incomprehensible.  
Training on 4 v100 using the same config file as tacotron_float.py. The only difference is that i am not using horovod. 
![train](https://user-images.githubusercontent.com/17470250/53898459-b5bf4e00-3ffd-11e9-8783-4d6deae1ed73.png)

Looked at issue #302 and #345 and it seems like the issue was a smaller batch size however i am using the default batch size of 48. Should i train it with a larger batch size? or is the issue with not using horovod? Let me know if there is anything i can try to produce better results.

also the train_audio sounds good in tensorboard

Thanks :)

**Comment by blisc** [comment]
Train audio will always sound good due to teacher forcing. Train loss is also not a good measure of convergence.
The best test for convergence is whether your attention weights are close to diagonal.
Please try the 1 gpu config and see if it works. Use all of LJSpeech for training (ie do not make a validation or test split)

**Comment by mehulsuresh** [comment]
Thanks for your quick response! 
Where can i see the attention plot? 
I am using all of the data. 
Will try running the model as 1gpu and also with the nvidia-docker container and report back.

**Comment by blisc** [comment]
By default, it should log to tensorboard under images.
If it is not in tensorboard, it is probably saved to your logdir as png file

**Comment by mehulsuresh** [comment]
![output_step0_0_infer](https://user-images.githubusercontent.com/17470250/54040018-f6e46900-4189-11e9-99e4-c42b0e8b3e72.png)
This is what it looks like

**Comment by mehulsuresh** [comment]
![individualimage](https://user-images.githubusercontent.com/17470250/54040511-29db2c80-418b-11e9-85b9-b65d05582a76.png)

**Comment by blisc** [comment]
Your plot for alignments is not very good. So it is pretty clear indication that the eval audio will be bad. A good plot for alignments would be a clear diagonal line starting from the bottom right corner.
Try changing https://github.com/NVIDIA/OpenSeq2Seq/blob/master/example_configs/text2speech/tacotron_float.py#L16
from "both" to "mel"

**Comment by mehulsuresh** [comment]
Ok.. Tried training with the docker container and was able to get the expected results 
![individualImage (1)](https://user-images.githubusercontent.com/17470250/54369588-2ee52380-4644-11e9-832c-450a04540187.png)

However noticed some issues
1 . After training with mixed precision infer doesnt work because of this error 
`TypeError: Input 'wci' of 'LSTMBlockCell' Op has type float32 that does not match type float16 of argument 'x'.`

2. Tried trained the model with docker and very similar config file on much larger dataset from MAILABS and it was not able to produce good results. 
![individualImage](https://user-images.githubusercontent.com/17470250/54370115-132e4d00-4645-11e9-8582-b7903526c82b.png)

Changes to fig files were as follows 
`dataset = "MAILABS"
dataset_location = "/var/log/nginx/MAILABS"
output_type = "both"
TO
dataset = "LJ"
dataset_location = "/var/log/nginx/LJSpeech"
output_type = "both"`
and
`batch_size = 55`

Trying to train on MAILABS with output_type="mel"

will report back if the results improve.

Attached Config file used 
[british.zip](https://github.com/NVIDIA/OpenSeq2Seq/files/2967218/british.zip)

**Comment by blisc** [comment]
Regarding MAILABS, Tacotron is a single-speaker model so please ensure that all of your training data is from one speaker. I would even go as far as to only use a single book from a single speaker.

Do you know what the difference is between the docker container and what you were using before the container?

**Comment by mehulsuresh** [comment]
With MAILABS I'm using only one speaker but two books from the same speaker. After I changed output_type="mel", The network is still training but the results look a lot more promising 
![individualImage (2)](https://user-images.githubusercontent.com/17470250/54383274-aeccb700-465f-11e9-9fbd-28faabde446c.png) only 2500 epochs in. Not sure why changing 'both' to 'mel' makes it perform a better. 


The only thing that i feel is different from the old way of training to the docker container is horovod and slightly higher batch size, everything else is pretty much the same.

Also is it not possible to do inference when training it with mixed precision?

**Comment by mehulsuresh** [comment]
Looks like to only way to train on MAILABS dataset is to use "mel" instead of "both". However after training the inference audio is not as clear as LJspeech trained on "both".
[Audio_Samples.zip](https://github.com/NVIDIA/OpenSeq2Seq/files/2988960/Audio_Samples.zip)

**Comment by blisc** [comment]
Have you tried using the same books as the ones published in our documentation?
“Jane Eyre” read by Elizabeth Klett
“North And South” read by Mary Ann

**Comment by mehulsuresh** [comment]
Yeah trained it on Jane Eyre by Elizabeth Klett.

**Comment by blisc** [comment]
If you want, you can try to use a neural vocoder (WaveGlow or WaveNet) to improve your audio quality.
