### ISSUE TITLE
WER in speech recognition in inference mode

### ISSUE THREAD

**Issue by inchpunch** [NVIDIA/OpenSeq2Seq#379]
Wondering where to find WER for the inference mode? 

I tried the toy example and the small DS2 model

python run.py --config_file=example_configs/speech2text/ds2_toy_config.py --mode=infer --infer_output_file=ds2_toy_out.txt

python run.py --config_file=example_configs/speech2text/ds2_small_1gpu.py --mode=infer --infer_output_file=ds2_out.txt

But the screen output only says "*** Finished inference" without showing the WER. The output file does not contain WER either.

**Comment by borisgin** [comment]
WER is printed in the eval mode. WER for inference is not defined since we don't have ground truth
