### ISSUE TITLE
Adding custom hooks

### ISSUE THREAD

**Issue by w4-anthony** [NVIDIA/OpenSeq2Seq#381]
I would like to have the ability to add a custom hook through the configuration file. Is that a feature that would be desirable? If so, I could work on a PR for that.

**Comment by borisgin** [comment]
Hi, can you give some example how you would use such hooks, please?

**Comment by w4-anthony** [comment]
Hi Boris,
The idea would be to define a hook in the train_params dictionary in your config file. Something like:

train_params = {
  "data_layer": ...
  ...
  "hooks": [MyHook]
}

Where MyHook would be a class derived from tf.train.SessionRunHook and it would be passed along to the train() function in open_seq2seq/utils/funcs.py.

I'm not super familiar with OpenSeq2Seq code base yet, but it looks like it's feasible. What do you think?

**Comment by borisgin** [comment]
This can be useful, for example to add logging hooks. Yes, please open PR

**Comment by okuchaiev** [comment]
this was merged to master, closing
