### ISSUE TITLE
Training details of jasper10x5_LibriSpeech_nvgrad

### ISSUE THREAD

**Issue by GabrielLin** [NVIDIA/OpenSeq2Seq#415]
Could you please show me more details of jasper10x5_LibriSpeech_nvgrad pre-train model? Such as hardware, training time, whether to use external data or not, whether to use synthetic data or not. Thanks.

**Comment by okuchaiev** [comment]
@blisc could you please comment on this

**Comment by blisc** [comment]
The pre-trained model can be achieved as is with the jasper10x5_LibriSpeech_nvgrad.py example config.
- No data external to LibriSpeech is used (no synthetic data was used).
- We used 3-fold speed perturbation (0.9, 1.0, 1.1) as data augmentation
- It was done on 8xV100

In additional, compared to older Jasper models:
- We switched from python_speech_features to librosa for pre-processing
- We switched from SGD to Novograd
- We added dithering
- Input spectrogram is now normalized per frequency bin as opposed to over the whole spectrogram

**Comment by GabrielLin** [comment]
Thank you for your valuable information. @blisc
