### ISSUE TITLE
NameError: name 'psf' is not defined

### ISSUE THREAD

**Issue by vinnitu** [NVIDIA/OpenSeq2Seq#432]
how to define psf?

now I add backend librosa to data_layer_params

**Comment by vsl9** [comment]
Did you install `python_speech_features` package? 
We started development with `python_speech_features` and then switched to `librosa`. By default, backend is `psf` (`python_speech_features`) for backward compatibility, so there is no need to define `psf` backend. Just make sure that you installed `python_speech_features`. Though, we recommend to use newer `librosa` backend which has numerous important features (like windowing, more accurate mel scale aggregation, etc.).
