### ISSUE TITLE
Audio captioning

### ISSUE THREAD

**Issue by gioannideImp** [NVIDIA/OpenSeq2Seq#436]
Hello team, does OpenSeq2Seq support audio captioning (detecting the start time and end time of a predicted word)? Thanks.

**Comment by vsl9** [comment]
Hello George, there is an experimental tool for that. We tested it with Jasper models. First of all, you'll need to install Baidu's beam search decoder:
```
scripts/install_decoders.sh
```
Then please follow these instructions: https://nvidia.github.io/OpenSeq2Seq/html/speech-recognition/speech-to-text-align.html

**Comment by gioannideImp** [comment]
Thank you @vsl9
