### ISSUE TITLE
Wave2Letter+

### ISSUE THREAD

**Issue by gioannideImp** [NVIDIA/OpenSeq2Seq#437]
Hello, I have came up with a problem while training Wave2Letter+ on the LibriSpeech dataset from scratch. The terminal displays:

> WARNING: tensorflow: It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 10835 vs. previous value: 10835. You could increase the global step by passing tf.train.get_global_step() to Optimiser.apply_gradients or Optimiser.minimize.

This has happened twice in a row. The first time I thought something may have gone wrong so I restarted the training and when it reached the same step again, it displayed the same error. The training is ran on 4 GPUs Tesla K80.

**Comment by borisgin** [comment]
This is related to mixed precision. K80 does not support float16, so you’d better switch to float.

**Comment by gioannideImp** [comment]
Thank you @borisgin

**Comment by rusiaaman** [comment]
@borisgin I am facing the same issue but on Tesla T4. Any pointers?
