### ISSUE TITLE
Out of system RAM when training Centaur

### ISSUE THREAD

**Issue by BoneGoat** [NVIDIA/OpenSeq2Seq#438]
I'm running out of system RAM when training using the example for Centaur. My system has 16GB RAM and 16GB swap. The training will eat RAM until the system will kill the process. I added an additional 32GB of swap and the training will also consume that until killed.

The CPU is loaded to 100% on 4 cores and my GTX1080 is loaded to about 50% proc and 60% mem. The training will create checkpoints which I can load into Tensorboard which has nice results but I would rather have it train until finished without being killed. So, has anyone else seen this problem?

**Comment by borisgin** [comment]
Can you change flag **debug=True**  in the config and attach the log file, please?

**Comment by BoneGoat** [comment]
[centaur_float.log](https://github.com/NVIDIA/OpenSeq2Seq/files/3194365/centaur_float.log)

**Comment by BoneGoat** [comment]
[jasper_infer_oom.log](https://github.com/NVIDIA/OpenSeq2Seq/files/3201552/jasper_infer_oom.log)

Another possible OOM situation: Inference on jasper10x5_LibriSpeech_nvgrad.py will also consume all system RAM before getting killed. This is on another system with 32GB RAM, 32GB swap and a RTX2080Ti.

**Comment by borisgin** [comment]
Can you try with smaller batch size per GPU please?

**Comment by BoneGoat** [comment]
I tried using a batch size of 4 but something must have broke because now it won't run because of this:

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [60] rhs shape= [53]
	 [[node save/Assign (defined at /root/dev/git/OpenSeq2Seq/open_seq2seq/utils/funcs.py:209) ]]
	 [[node save/RestoreV2 (defined at /root/dev/git/OpenSeq2Seq/open_seq2seq/utils/funcs.py:209) ]]

It's using the exact same checkpoint so I'm not sure what happend.

**Comment by blisc** [comment]
Try decreasing beam_width from 2048 to 32
