### ISSUE TITLE
Clarity regarding vocab_file parameter in the config

### ISSUE THREAD

**Issue by shiv6146** [NVIDIA/OpenSeq2Seq#445]
@blisc @borisgin What exactly does vocab_file mean? Should it be changed when different datasets are used or does it remain the same (27 symbols) irrespective of the dataset used? Does it make sense to use the `trie_vocab.txt` obtained after `download_lm.sh` for Librispeech to get better results?

**Comment by vsl9** [comment]
`vocab_file` is actually an alphabet, that is, a set of characters which a model can emit at each time step. There are 28 symbols in normalized LibriSpeech: 26 English characters + apostrophe + space. A CTC acoustic model has an additional CTC blank symbol. Of course, you can extend this alphabet for other datasets (see for example https://github.com/NVIDIA/OpenSeq2Seq/issues/443). `trie_vocab.txt` is a set of all words in LibriSpeech which is required for building a prefix tree (trie).

**Comment by shiv6146** [comment]
@vsl9 Thanks for your insights :+1: This helps!
