### ISSUE TITLE
Training with a dataset other than LibriSpeech

### ISSUE THREAD

**Issue by kourouklides** [NVIDIA/OpenSeq2Seq#446]
Hi, I am trying to train with a new dataset other than LibriSpeech and I have formatted the data-set to be 16KHz wav files and the csv files the same as the ones LibriSpeech format is.

However, train, train_eval and eval modes do not work and they throw an error saying "KeyError: H". Infer mode works and successfully produces a infer-out.txt file. Please let me know what is the problem here.

**Comment by borisgin** [comment]
Can you attach the complete log file please?

**Comment by vsl9** [comment]
H, it looks like your ground truth transcriptions contain a capital letter H. We use the following alphabet for LibriSpeech: [" ", "a", "b", ..., "z", "'"]. It can be found in a vocab file. All ground truth transcriptions should contain only characters from the alphabet.

**Comment by kourouklides** [comment]
Thank you very much. It has been resolved.
