### ISSUE TITLE
Question: why cudnn gru performs better than vanilla tensorflow gru?

### ISSUE THREAD

**Issue by wanglouis49** [NVIDIA/OpenSeq2Seq#450]
I have run Deep Speech 2 models, both small and large, with or without cudnn. I notice the model using cudnn converges much faster even though other settings are exactly the same. To clarify, I mean eval_loss/wer vs step instead of training time. Any expert on cudnn could answer why is this happening?

**Comment by borisgin** [comment]
Was training in float or in mixed precision?

**Comment by wanglouis49** [comment]
It's in float32. No mixed precision.

**Comment by borisgin** [comment]
Cudnn GRU is slightly different from TF GRU: see [https://www.tensorflow.org/api_docs/python/tf/contrib/cudnn_rnn/CudnnCompatibleGRUCell](url)

**Comment by wanglouis49** [comment]
It is interesting to know that it causes a considerably big difference in this case. Thanks.
