### ISSUE TITLE
GPU suggestions

### ISSUE THREAD

**Issue by c-charalampous** [NVIDIA/OpenSeq2Seq#454]
Hello team, I was wondering what would be the difference of using a K80 Tesla GPU vs. RTX 2080 TI. Which one would be better? I have seen the specs, it seems the RTX has a higher GPU bandwidth but I am not sure if it supports float16 for mixed precision training. Any thoughts on this? 
Thanks.

**Comment by borisgin** [comment]
Take a look at [https://lambdalabs.com/blog/2080-ti-deep-learning-benchmarks/](url) .
