### ISSUE TITLE
Would you mind tell me the WER of librispeech datasets? thanks

### ISSUE THREAD

**Issue by iamxiaoyubei** [NVIDIA/OpenSeq2Seq#468]
Would you mind tell me the WER of librispeech datasets(dev-clean/dev-other/test-clean/test-other/or both of them?) for ASR task? Thank you~

**Comment by borisgin** [comment]
[ASR WER](https://nvidia.github.io/OpenSeq2Seq/html/speech-recognition.html)

**Comment by iamxiaoyubei** [comment]
Your results are really good!

Are these results obtained using only the librispeech dataset for training? If not, could you tell me which datasets are used in total or how long are they? Thank you!

**Comment by borisgin** [comment]
Only Librispeech.
