### ISSUE TITLE
Ensemble Learning

### ISSUE THREAD

**Issue by flassTer** [NVIDIA/OpenSeq2Seq#475]
Hello NVIDIA,

I am training some models on different datasets. It has come to my notice that when transfer learning, the model starts becoming better for the new dataset but its performance worsens on the previous. Therefore I decided to use ensemble learning to fix this. I have considered using AdaBoost (https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html)

How could the sklearn implementation of this method be used with OpenSeq2Seq or an ensemble learning boosting approach in general?

**Comment by borisgin** [comment]
If you use AdaBoost with Tensorflow, you can or use [ScipyOptimizerInterface](https://www.tensorflow.org/api_docs/python/tf/contrib/opt/ScipyOptimizerInterface) API, or implement new optimizer (see for example [tf/contrib/optimizers](https://www.tensorflow.org/api_docs/python/tf/contrib/optimizer_v2)
