### ISSUE TITLE
Is clipped ReLU used in Jasper?

### ISSUE THREAD

**Issue by vadimkantorov** [NVIDIA/OpenSeq2Seq#486]
https://nvidia.github.io/OpenSeq2Seq/html/speech-recognition/jasper.html says that Clipped ReLU is used. However in the source code it's just [`"activation_fn" : tf.nn.relu`](https://github.com/NVIDIA/OpenSeq2Seq/blob/master/example_configs/speech2text/jasper10x5_LibriSpeech_nvgrad_masks.py#L156)

Thanks!

**Comment by borisgin** [comment]
We use regular ReLU, clipped ReLU is optional

**Comment by vadimkantorov** [comment]
thanks!
