### ISSUE TITLE
Config file for Fisher+Switchboard?

### ISSUE THREAD

**Issue by Shujian2015** [NVIDIA/OpenSeq2Seq#488]
Hi, thanks for open source this awesome package. Is there any plan to add the config file for Fisher+Switchboard datasets?

**Comment by borisgin** [comment]
Currently we don't plan to add config file for Fisher-SWB. 
But  PR for downloading and training CommonVoice would be welcomed :)

**Comment by Shujian2015** [comment]
Hi @borisgin, thanks for your response. Is there any particular reason that for fisher_swb data, Jasper DR 10x5 was trained using SGD with momentum but not NovoGrad and it is only trained for 50 epochs instead of 400?

**Comment by borisgin** [comment]
No particular reason, just lack of time before Interspeech deadline

**Comment by Shujian2015** [comment]
Thanks again @borisgin !

**Comment by Shujian2015** [comment]
Hi @borisgin, how did you handle things like <silence>, [breath], [cough] in this dataset? Did you put them into vocab, or just delete them, or any other methods? Thanks in advance.
