### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'SessionRunHook'

### ISSUE THREAD

**Issue by shubhamsingh987** [NVIDIA/OpenSeq2Seq#540]
Im using tf==2.2.0
Any fix for this error?

**Comment by darren0h** [comment]
!pip install tensorflow-gpu==1.15

**Comment by darren0h** [comment]
> Im using tf==2.2.0
> Any fix for this error?

!pip install tensorflow-gpu==1.15

**Comment by dheerajmpai** [comment]
If you are using google colab use the ipython magic command

```
%tensorflow_version 1.x
```

**Comment by mrowan137** [comment]
Is there any fix for this issue without downgrading tensorflow?

**Comment by luca992** [comment]
`tf.train.SessionRunHook` was moved to `tf.estimator.SessionRunHook` it seems
