### ISSUE TITLE
Fix all deprecation warning

### ISSUE THREAD

**Issue by okuchaiev** [NVIDIA/OpenSeq2Seq#70]
Such as:

```
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.

```

**Comment by sukhoi** [comment]
@okuchaiev : I would like to start contributing to this project . can this issue be picked up at this stage of development ? Thanks.

**Comment by okuchaiev** [comment]
Absolutely! Please work based on this branch: 18.09-dev
