### ISSUE TITLE
Evaluation numbers are not exact when using num_gpus > 1

### ISSUE THREAD

**Issue by Kipok** [NVIDIA/OpenSeq2Seq#71]
This happens because all batches are split across GPUs in random order (because we use subsequent calls to tf.data.Iterator().get_next()). Thus, the last batch might be processed incorrectly when the dataset size is not divisible by the batch size.

**Comment by Kipok** [comment]
This is also fixed in v0.3

**Comment by blisc** [comment]
This was fixed assuming the decoder returns shape (BS, ...) which is not the case for all decoders (eg FC_decoders return (T, BS, num_feats)
