### ISSUE TITLE
Add Resnet50-based encoder to OpenSeq2Seq

### ISSUE THREAD

**Issue by okuchaiev** [NVIDIA/OpenSeq2Seq#75]

**Comment by okuchaiev** [comment]
Also, means adding new data layer for ImageNet with necessary augmentations

**Comment by okuchaiev** [comment]
@Kipok  please close if done

**Comment by okuchaiev** [comment]
@Kipok ping

**Comment by Kipok** [comment]
Yes, this is included into v0.3 version, closing this issue
